site_name: mkdocs smzhbook theme
repo_url: https://github.com/smallzh/mkdocs-smzhbook-theme

nav:
  - 首页: index.md
  - MkDocs 程序说明:
      - '导读': mkdocs/index.md
      - 'mkdocs.yml 配置': mkdocs/configuration.md
      - 'Markdown 文档写作': mkdocs/writing-your-docs.md
      - '构建流程全解析': mkdocs/build-process.md
      - '搜索插件原理': mkdocs/search.md
      - '自定义插件': mkdocs/custom-plugins.md
      - '自定义主题': mkdocs/custom-themes.md
  - 主题文档:
      - '主题总览与安装': theme/index.md
      - '定制与进阶配置': theme/advanced-config.md
      - '构建与性能优化': theme/performance.md
      - '发布到 PyPI': theme/publishing-to-pypi.md
  - 关于:
      - '关于我': about/about_me.md
      - 'License': about/license.md

theme:
  name: mkdocs
  custom_dir: smzhbook_theme

plugins:
  - search:
      lang: ['zh', 'en']
      separator: '[\s\-\.]+'
      min_search_length: 2
      prebuild_index: false
      indexing: full

markdown_extensions:
  - toc:
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
