[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mkdocs-smzhbook-theme"
version = "1.1"
description = "smallzh's book theme for MkDocs"
readme = "README.md"
license = "BSD-2-Clause"
authors = [
    {name = "smallzh", email = "smallzh@yeah.net"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: MkDocs",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Documentation",
]
dependencies = [
    "mkdocs>=1.5",
]

[project.urls]
Source = "https://github.com/smallzh/mkdocs-smzhbook-theme"

[project.entry-points."mkdocs.themes"]
smzhbook = "smzhbook_theme"

[tool.hatch.build]
include = ["/smzhbook_theme"]
